default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  port: 3306

development:
  <<: *default
  database: good_night_development

test:
  <<: *default
  database: good_night_test

production:
  <<: *default
  database: good_night_production
